"""Task 7 headline table from analysis/data/cells.csv -> analysis/headline.md.

One value per (workload, variant, chip, day): Go/Java/inference = median of the
valid fixed runs' headline; PostgreSQL/Mongo = knee throughput (knee.json ops).
Per $ uses results/cost.md on-demand rates. "tie" = the two chips' day ranges
overlap. ponytail: range overlap, not the bootstrap interval (checklist item 3).
"""
import csv, re, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TYPES = {"arm": "m9g.4xlarge", "amd": "m8a.4xlarge", "x86": "m8i.4xlarge"}
price = {c: float(re.search(rf"\| {t} \| ([0-9.]+)", (ROOT / "results/cost.md").read_text())[1])
         for c, t in TYPES.items()}

vals = {}  # (workload, variant) -> chip -> [(day, value)]
for r in csv.DictReader(open(ROOT / "analysis/data/cells.csv")):
    if not r["day_class"].startswith("task7") or r["set_aside"]:  # non-empty = reason it was set aside
        continue
    v = r["knee_throughput"] if r["workload"] in ("postgres", "mongo") else r["headline_median"]
    if v:
        vals.setdefault((r["workload"], r["variant"]), {}).setdefault(r["chip"], []).append(
            (r["day_class"][-2:], float(v)))

def fmt(x):
    return f"{x/1000:.1f}k" if x >= 1000 else f"{x:.1f}"

out = ["# Task 7 headline (generated by analysis/headline.py — do not edit by hand)", "",
       "Values per day (d1/d2 = first instance, d3 = second). Mean over days. "
       "Per $ = mean / on-demand $/h, normalised to x86 = 1.00. "
       "Ranking marks: `tie` when two chips' day ranges overlap.", "",
       "| workload | variant | arm (m9g) | amd (m8a) | x86 (m8i) | per $ arm / amd / x86 | ties |",
       "|---|---|---|---|---|---|---|"]
for (w, var), chips in sorted(vals.items()):
    if w == "net":
        continue  # net headline = instance cap; see facts + cells.csv cpu_cores_per_gbps_*
    cellstr, mean = {}, {}
    for c in TYPES:
        days = sorted(chips.get(c, []))
        if days:
            mean[c] = statistics.mean(v for _, v in days)
            cellstr[c] = " / ".join(f"{d} {fmt(v)}" for d, v in days)
    per = {c: mean[c] / price[c] for c in mean}
    base = per.get("x86")
    perstr = " / ".join(f"{per[c]/base:.2f}x" if base and c in per else "–" for c in TYPES)
    rng = {c: (min(v for _, v in chips[c]), max(v for _, v in chips[c])) for c in mean}
    ties = [f"{a}={b}" for i, a in enumerate(TYPES) for b in list(TYPES)[i+1:]
            if a in rng and b in rng and rng[a][0] <= rng[b][1] and rng[b][0] <= rng[a][1]]
    out.append(f"| {w} | {var} | {cellstr.get('arm','–')} | {cellstr.get('amd','–')} | "
               f"{cellstr.get('x86','–')} | {perstr} | {', '.join(ties) or '–'} |")
out += ["", f"Prices ($/h, results/cost.md): " + ", ".join(f"{c} {p}" for c, p in price.items())]

# Spot: 7-day median, us-east-1, all AZs, 2026-09-22..30 (slides/fuentes.md §10.3). Spot changes
# price, never performance, so per-$ is recomputed from the same Task 7 means.
SPOT = {"arm": 0.3464, "amd": 0.3592, "x86": 0.3695}
out += ["", "## Per $ at Spot (7-day median us-east-1, 2026-09-22..30)", "",
        "| workload | variant | on-demand arm / amd vs x86 | Spot arm / amd vs x86 |", "|---|---|---|---|"]
for (w, var), chips in sorted(vals.items()):
    if w == "net" or not all(c in chips for c in TYPES):
        continue
    mean = {c: statistics.mean(v for _, v in chips[c]) for c in TYPES}
    od = {c: mean[c] / price[c] / (mean["x86"] / price["x86"]) for c in ("arm", "amd")}
    sp = {c: mean[c] / SPOT[c] / (mean["x86"] / SPOT["x86"]) for c in ("arm", "amd")}
    out.append(f"| {w} | {var} | {od['arm']:.2f}x / {od['amd']:.2f}x | {sp['arm']:.2f}x / {sp['amd']:.2f}x |")
out += ["", "Spot varies a lot by AZ (m8i $0.29-0.40 over the week): say \"weekly median in us-east-1\"."]

# Task 8 arc: Java stock, one fixed run per family (r2 = second node, m8g only).
rate = lambda t: float(re.search(rf"\| {re.escape(t)} \| ([0-9.]+)", (ROOT / "results/cost.md").read_text())[1])
arc = {}
for r in csv.DictReader(open(ROOT / "analysis/data/cells.csv")):
    if "task8" in r["results_dir"] and r["headline_median"]:
        arc.setdefault(r["variant"], (r["instance_type"], []))[1].append(float(r["headline_median"]))
if arc:
    t5, v5 = arc["m5"][0], statistics.mean(arc["m5"][1])
    out += ["", "## Task 8 generational arc (Java stock, 1 fixed run per family; orientative)", "",
            "Same scale as Task 7: arc m9g 80k = Task 7 arm-stock 80k; arc m8a 90k = Task 7 amd-stock 88-90k.", "",
            "| family | instance | rps knee | vs m5 raw | $/h | vs m5 per $ |", "|---|---|---|---|---|---|"]
    order = ["m5", "m6i", "m7i", "m8i", "m8a", "m6g", "m7g", "m8g", "m9g"]
    for f in [f for f in order if f in arc]:
        t, vs = arc[f]; v = statistics.mean(vs)
        runs = " (" + " / ".join(fmt(x) for x in vs) + ", 2 nodes)" if len(vs) > 1 else ""
        out.append(f"| {f} | {t} | {fmt(v)}{runs} | {v/v5:.2f}x | {rate(t)} | "
                   f"{(v/rate(t))/(v5/rate(t5)):.2f}x |")
(ROOT / "analysis/headline.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
